import LargeLogo from "../../assets/svg/logo-lg.svg";
import { Delivery } from "./types";

export const LIST: Delivery[] = [
  {
    id: 0,
    title: "제목입니다.",
    price: 1234,
    originalPrice: 12345,
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    region: "아이템 1",
    maxPeopleNumber: 4,
    contents: "asdf",
    location: "",
  },
  {
    id: 0,
    title: "제목입니다.",
    price: 1234,
    originalPrice: 12345,
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    region: "아이템 1",
    maxPeopleNumber: 4,
    contents: "asdf",
    location: "",
  },
  {
    id: 0,
    title: "제목입니다.",
    price: 1234,
    originalPrice: 12345,
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    region: "아이템 1",
    maxPeopleNumber: 4,
    contents: "asdf",
    location: "",
  },
  {
    id: 0,
    title: "제목입니다.",
    price: 1234,
    originalPrice: 12345,
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    region: "아이템 1",
    maxPeopleNumber: 4,
    contents: "asdf",
    location: "",
  },
  {
    id: 0,
    title: "제목입니다.",
    price: 1234,
    originalPrice: 12345,
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    region: "아이템 1",
    maxPeopleNumber: 4,
    contents: "asdf",
    location: "",
  },
];
