import LargeLogo from "../../assets/svg/logo-lg.svg";

export const LIST = [
  {
    id: 0,
    title: "제목입니다.",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 1",
    limit: 4,
    userId: 123,
  },
  {
    id: 1,
    title: "제목입니다요.",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 2",
    limit: 4,
    userId: 234,
  },
  {
    id: 2,
    title: "제목입니다요요",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 3",
    limit: 4,
    userId: 345,
  },
  {
    id: 3,
    title: "제목입니다.",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 1",
    limit: 4,
    userId: 123,
  },
  {
    id: 4,
    title: "제목입니다요.",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 2",
    limit: 4,
    userId: 234,
  },
  {
    id: 5,
    title: "제목입니다요요",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 3",
    limit: 4,
    userId: 345,
  },
  {
    id: 6,
    title: "제목입니다.",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 1",
    limit: 4,
    userId: 123,
  },
  {
    id: 7,
    title: "제목입니다요.",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 2",
    limit: 4,
    userId: 234,
  },
  {
    id: 8,
    title: "제목입니다요요",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 3",
    limit: 4,
    userId: 345,
  },
  {
    id: 9,
    title: "제목입니다.",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 1",
    limit: 4,
    userId: 123,
  },
  {
    id: 10,
    title: "제목입니다요.",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 2",
    limit: 4,
    userId: 234,
  },
  {
    id: 11,
    title: "제목입니다요요",
    price: 1234,
    category: "재료",
    endAt: new Date().toLocaleString(),
    filePath: LargeLogo,
    placeName: "아이템 3",
    limit: 4,
    userId: 345,
  },
];
